### ISSUE TITLE
 jupytergis_lab.GISDocument.add_geojson_layer opening only first entry in layer

### ISSUE THREAD

**Issue by matthewfeickert** [geojupyter/jupytergis#318]
This is a migration of a discussion with @mfisher87 in Discussion https://github.com/geojupyter/jupytergis/discussions/312, for additional information and examples please refer to the Discussion.

## Issue Summary

In [`jupytergis` `v0.2.0`](https://github.com/geojupyter/jupytergis/releases/tag/v0.2.0) when adding a GeoJSON layer to a `jupytergis_lab.GISDocument` with [jupytergis_lab.GISDocument.add_geojson_layer](https://jupytergis.readthedocs.io/en/latest/python_api.html#gisdocument-api-reference) only the first entry in the layer is displayed in the document Jupyter render.

## Expected Results

I would expect that all entries in the GeoJSON layer would be added and rendered.

## Steps to Reproduce

(See the end of this Issue for a full reproducer `pixi` manifest `pixi.toml`. Or just use [this GitHub Gist](https://gist.github.com/matthewfeickert/c472143dae11af989b3c6d531d2c605c).)

Here I'll use [`pixi`](https://pixi.sh/) and get everything from conda-forge, but a similar environment can be created with `conda`/`mamba` and conda-forge or with `pip`/`uv` and PyPI.

```console
$ mkdir -p /tmp/reproducer && cd /tmp/reproducer
$ pixi init
$ pixi add 'jupytergis=0.2.0' git jq
$ pixi run 'git clone https://github.com/geojupyter/jupytergis.git && cd jupytergis && git reset --hard 96cef85ae8edf6948e4e7d3b9b24c5a061e473c2'
$ pixi run 'cd jupytergis && jupyter lab examples/Notebook.ipynb'
```

Execute the first 5 cells of the [`examples/Notebook.ipynb`](https://github.com/geojupyter/jupytergis/blob/96cef85ae8edf6948e4e7d3b9b24c5a061e473c2/examples/Notebook.ipynb), which are

```python
# Cell 1
from jupytergis_lab import GISDocument

# Cell 2
doc = GISDocument("france_hiking.jGIS")

# Cell 3
doc

# Cell 4
doc.add_raster_layer(
    url="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
    name="Google Satellite",
    attribution="Google",
    opacity=0.6,
)

# Cell 5
doc.add_geojson_layer(path="france_regions.json")
```

which produces

![image](https://github.com/user-attachments/assets/0fe252ae-b437-4841-8f6c-9a844eeae0d3)

The resulting rendered `doc` object in Jupyter Lab shows only the first entry in the GeoJSON layer added with

```python
doc.add_geojson_layer(path="france_regions.json")
```

which is [Île-de-France](https://en.wikipedia.org/wiki/%C3%8Ele-de-France#/map/0)

```console
$ pixi run jq '.. | objects | .nom? | select(. != null)' jupytergis/examples/france_regions.json 
"Île-de-France"
"Centre-Val de Loire"
"Bourgogne-Franche-Comté"
"Normandie"
"Hauts-de-France"
"Grand Est"
"Pays de la Loire"
"Bretagne"
"Nouvelle-Aquitaine"
"Occitanie"
"Auvergne-Rhône-Alpes"
"Provence-Alpes-Côte d'Azur"
"Corse"
```

while I would expect that all the polygons in the layer [`examples/france_regions.json`](https://github.com/geojupyter/jupytergis/blob/96cef85ae8edf6948e4e7d3b9b24c5a061e473c2/examples/france_regions.json) would be added and displayed.

![image](https://github.com/user-attachments/assets/f44bcfab-2b26-4436-8d1a-e92b96b215f7)

## Environment summary

Full `pixi.toml` manifest that allows for running everything described in this Issue via `pixi run start` on any x86 Linux machine or any macOS machine:

```toml
[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "reproducer"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
clone = """
rm -rf jupytergis && \
git clone https://github.com/geojupyter/jupytergis.git && \
cd jupytergis && \
git reset --hard 96cef85ae8edf6948e4e7d3b9b24c5a061e473c2
"""

check-regions = """
jq '.. | objects | .nom? | select(. != null)' jupytergis/examples/france_regions.json
"""

example = """
cd jupytergis && \
jupyter lab examples/Notebook.ipynb
"""

start = { depends-on = ["clone", "check-regions", "example"] }

[dependencies]
jupytergis = "0.2.0.*"
git = ">=2.47.1,<3"
jq = ">=1.7.1,<2"
```

Relevant environment information:

```console
$ pixi list python
Package                Version         Build               Size       Kind   Source
brotli-python          1.1.0           py312h2ec8cdc_2     341.7 KiB  conda  brotli-python
ipython                8.31.0          pyh707e725_0        586.7 KiB  conda  ipython
python                 3.12.8          h9e4cc4f_1_cpython  30.1 MiB   conda  python
python-dateutil        2.9.0.post0     pyhff2d567_1        217.3 KiB  conda  python-dateutil
python-fastjsonschema  2.21.1          pyhd8ed1ab_0        221 KiB    conda  python-fastjsonschema
python-json-logger     2.0.7           pyhd8ed1ab_0        13.1 KiB   conda  python-json-logger
python_abi             3.12            5_cp312             6.1 KiB    conda  python_abi
types-python-dateutil  2.9.0.20241206  pyhd8ed1ab_0        21.6 KiB   conda  types-python-dateutil
$ pixi list jupyter
Package                   Version  Build         Size       Kind   Source
jupyter-collaboration     3.1.0    pyhd8ed1ab_0  9.6 KiB    conda  jupyter-collaboration
jupyter-collaboration-ui  1.1.0    pyhd8ed1ab_0  36.5 KiB   conda  jupyter-collaboration-ui
jupyter-docprovider       1.1.0    pyhd8ed1ab_1  32.4 KiB   conda  jupyter-docprovider
jupyter-lsp               2.2.5    pyhd8ed1ab_1  53.9 KiB   conda  jupyter-lsp
jupyter_client            8.6.3    pyhd8ed1ab_1  103.8 KiB  conda  jupyter_client
jupyter_core              5.7.2    pyh31011fe_1  56.3 KiB   conda  jupyter_core
jupyter_events            0.11.0   pyhd8ed1ab_0  21.6 KiB   conda  jupyter_events
jupyter_server            2.15.0   pyhd8ed1ab_0  320.1 KiB  conda  jupyter_server
jupyter_server_fileid     0.9.2    pyhd8ed1ab_1  20 KiB     conda  jupyter_server_fileid
jupyter_server_terminals  0.5.3    pyhd8ed1ab_1  19.2 KiB   conda  jupyter_server_terminals
jupyter_server_ydoc       1.1.0    pyhd8ed1ab_0  27.5 KiB   conda  jupyter_server_ydoc
jupyter_ydoc              2.1.3    pyhd8ed1ab_0  36 KiB     conda  jupyter_ydoc
jupytergis                0.2.0    pyhd8ed1ab_0  9.3 KiB    conda  jupytergis
jupytergis_core           0.2.0    pyhd8ed1ab_0  17.8 MiB   conda  jupytergis_core
jupytergis_lab            0.2.0    pyhd8ed1ab_0  39.1 KiB   conda  jupytergis_lab
jupytergis_qgis           0.2.0    pyhd8ed1ab_0  34.9 KiB   conda  jupytergis_qgis
jupyterlab                4.3.4    pyhd8ed1ab_0  6.9 MiB    conda  jupyterlab
jupyterlab_pygments       0.3.0    pyhd8ed1ab_2  18.3 KiB   conda  jupyterlab_pygments
jupyterlab_server         2.27.3   pyhd8ed1ab_1  48.3 KiB   conda  jupyterlab_server
```

This is also provided in full with the `pixi` environment lock file in the following GitHub Gist: https://gist.github.com/matthewfeickert/c472143dae11af989b3c6d531d2c605c

Hash level reproduction can be achieved on any x86 Linux machine or any macOS machine with the following:

```
git clone https://gist.github.com/c472143dae11af989b3c6d531d2c605c.git jupytergis-issue-318 && cd jupytergis-issue-318 && pixi run start
```
