### ISSUE TITLE
Document building docs locally

### ISSUE THREAD

**Issue by mfisher87** [geojupyter/jupytergis#432]
We don't have documentation for locally building the docs yet. The easier we make this, the less we have to document!

Working on the docs takes some setup: create the environment from `environment-docs.yml`, activate the envirionment, run an incantation. Make a change, run the incantation again.

It would be nice to make building the docs a single-command affair. For example, I can do this with Pixi configuration (replacing docs/environment-docs.yml`), so the single command `pixi run build` from the `docs/` directory will setup the env and build the docs:

```toml
[project]
authors = ["JupyterGIS team"]
channels = ["conda-forge"]
description = "For building JupyterGIS docs"
name = "docs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "python -m sphinx -T -b html -d _build/doctrees -D language=en . ./_html"

[dependencies]
python = "3.12"
# Build docs & JupyterLite
jupyterlite-core = ">=0.4.0,<0.6.0"
jupyterlite-xeus = ">=2,<3"
jupyterlite-sphinx = "*"
sphinx = "*"
sphinx-tabs = "*"
pydata-sphinx-theme = "*"
sphinx-autodoc-typehints = "*"
sphinx-exercise = "*"
sphinx-togglebutton = "*"

xeus-python = "*"  # TODO: Do we need this?

[pypi-dependencies]
myst-parser = "*"
setuptools = "*"
```

Is there another way we can achieve single-command docs build? Perhaps Nox? 🤷 What tools do y'all like that can achieve this?
